coverage:
  status:
    project:
      default:
        target: auto
        threshold: 80%
        base: auto
        if_ci_failed: error
        flags:
          - unit
        paths:
          - src
    patch:
      default:
        target: auto
        threshold: 0%
        base: auto
        branches:
          - master
        if_ci_failed: error
        only_pulls: false
        flags:
          - unit
        paths:
          - src
