name: Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install -q uv
          python -m uv sync --no-group lint

      - name: Run tests and generate coverage report
        run: |
          .venv/bin/python -m pytest --cov --cov-report=xml

      - name: Check code coverage for changed lines
        if: ${{ matrix.python-version == '3.12' }}
        # Check coverage (80% or more) if more than 20 lines changed
        run: |
          python -m pip install diff_cover==9.4.1
          diff-cover coverage.xml --format json:report.json
          num_lines=$(jq '.["total_num_lines"]' report.json)
          percent_covered=$(jq '.["total_percent_covered"]' report.json)
          test $num_lines -le 20 || test $percent_covered -ge 80

      - name: Check total code coverage
        if: ${{ matrix.python-version == '3.12' }}
        run: |
          .venv/bin/python -m coverage report --fail-under=80
